version: '3'

services:
  snipeit:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    container_name: snipeit
    ports:
    - "8084:80"
    volumes:
    - logs:/var/www/html/storage/logs
    - source:/var/www/html
    depends_on:
    - snipedb
    - redis
    env_file:
    - .env.docker
    networks:
    - snipeit-backend

  snipedb:
    image: mariadb:10.6.4-focal
    volumes:
    - db:/var/lib/mysql
    env_file:
    - .env.docker
    networks:
    - snipeit-backend
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2.5-buster
    networks:
    - snipeit-backend

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
    # - 1025:1025
    - "8025:8025"
    networks:
    - snipeit-backend


volumes:
  db: {}
  logs:
    driver: local
    driver_opts:
      type: none
      device: /home/tungpx/logs
      o: bind
  source:
    driver: local
    driver_opts:
      type: none
      device: /home/tungpx/source
      o: bind

    
networks:
  snipeit-backend: {}
